export const STORE_INIT = '@@PM_REACT_STORE_INIT'

export const ACTIONS_SEPARATOR = '|'

export const ASYNC_ACTION_PENDING_SUFFIX = '_PENDING'
export const ASYNC_ACTION_FULFILLED_SUFFIX = '_FULFILLED'
export const ASYNC_ACTION_REJECTED_SUFFIX = '_REJECTED'
